---- Tạo database ----

CREATE DATABASE COFFEE_SHOP_MANAGEMENT

USE COFFEE_SHOP_MANAGEMENT

SET DATEFORMAT DMY 

---- Xóa các table ----

DROP TABLE CTHD
DROP TABLE HOADON
DROP TABLE KHACHHANG
DROP TABLE CHITIETMON
DROP TABLE MON
DROP TABLE ACCOUNT
DROP TABLE NHANVIEN
DROP TABLE QUAN
DROP TABLE CHUQUAN

---- Tạo các table ----

--  Đặt tên các mã
-- Ví dụ 
-- NV0001		4 số
-- KH0000000001 10 số
-- MON001 3 số


CREATE TABLE CHUQUAN(
	USERNAME NVARCHAR(100) PRIMARY KEY,
	PASS NVARCHAR(1000),
	HOTEN NVARCHAR(100),
	GIOITINH NVARCHAR(100),
	DIACHI NVARCHAR(100),
	CMND NVARCHAR(100),
	SDT NVARCHAR(100)
)

CREATE TABLE QUAN(
	SDT NVARCHAR(100) PRIMARY KEY,
	TENQUAN NVARCHAR(100), 
	DIACHI NVARCHAR(100), 
	SLOGAN NVARCHAR(1000), 
	SINHNHAT SMALLDATETIME, 
	SLNV INT, 
	LOINHACNHO NVARCHAR(1000), 
	LOICHUC NVARCHAR(1000)
)

CREATE TABLE NHANVIEN(
	MANV NVARCHAR(100) PRIMARY KEY, 
	HOTEN NVARCHAR(100),
	GIOITINH NVARCHAR(100), 
	DIACHI NVARCHAR(100), 
	CMND NVARCHAR(100), 
	SDT NVARCHAR(100), 
	NGAYVL SMALLDATETIME, 
	LUONG INT, 
	CHUCVU NVARCHAR(100)
)

CREATE TABLE ACCOUNT(
	MANV NVARCHAR(100) PRIMARY KEY,
	USERNAME NVARCHAR(100),
	PASS NVARCHAR(1000),
	TINHTRANG NVARCHAR(100),
	CONSTRAINT FK_ACCOUNT_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
)

CREATE TABLE MON(
	MAMON NVARCHAR(100) PRIMARY KEY, 
	TENMON NVARCHAR(100), 
	DVT NVARCHAR(100), 
	NUOCSX NVARCHAR(100), 
	SOLANPHUCVU INT
)

CREATE TABLE CHITIETMON(
	MAMON NVARCHAR(100) NOT NULL, 
	SIZE NVARCHAR(100) NOT NULL, 
	GIA INT,
	CONSTRAINT PK_CHITIETMON PRIMARY KEY(MAMON, SIZE),
	CONSTRAINT FK_CHITIETMON_MAMON FOREIGN KEY (MAMON) REFERENCES MON(MAMON)
)

CREATE TABLE KHACHHANG(
	MAKH NVARCHAR(100) PRIMARY KEY,  
	HOTEN NVARCHAR(100),
	SDT NVARCHAR(100), 
	GIOITINH NVARCHAR(100),
	NGAYSINH SMALLDATETIME, 
	NGAYDK SMALLDATETIME, 
	DOANHSO INT, 
	MONKHOAIKHAU NVARCHAR(100), 
	SOLANTOIQUAN INT, 
	MEMBER NVARCHAR(100)
)

CREATE TABLE HOADON(
	MAHD NVARCHAR(100) PRIMARY KEY, 
	MANV NVARCHAR(100), 
	MAKH NVARCHAR(100), 
	TENCT NVARCHAR(100),
	PTKM INT,
	TONGHOADON INT, 
	THANHTIEN INT, 
	LOICHUC NVARCHAR(1000), 
	TENWF NVARCHAR(100),
	PASSWF NVARCHAR(100),
	NGHD SMALLDATETIME,
	CONSTRAINT FK_HOADON_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
	CONSTRAINT FK_HOADON_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
)

CREATE TABLE CTHD(
	MAHD NVARCHAR(100) NOT NULL, 
	MAMON NVARCHAR(100) NOT NULL, 
	SIZE NVARCHAR(100) NOT NULL,
	SL INT,
	CONSTRAINT PK_CTHD PRIMARY KEY(MAHD, MAMON, SIZE),
	CONSTRAINT FK_CTHD_MAHD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
	CONSTRAINT FK_CTHD_MAMON_SIZE FOREIGN KEY (MAMON, SIZE) REFERENCES CHITIETMON(MAMON, SIZE)
)

---- Tạo các thông tin ban đầu ----
