USE THECOFFEESHOP
GO

-- Delete data all table
DELETE FROM STOCK 
DELETE FROM BILLDETAIL 
DELETE FROM BILL 
DELETE FROM DISCOUNT 
DELETE FROM CUSTOMER 
DELETE FROM FOOD 
DELETE FROM ACCOUNT 
DELETE FROM ACCOUNTINFO 